force-app/main/default/objects/Data_Corruption_Object__mdt/Data_Corruption_Object__mdt.object-meta.xml
<CustomObject>
    <description>A custom metadata type to track sObjects and fields that should be corrupted by the Data Recovery Simulation code.</description>
    <label>Data Corruption Object</label>
    <pluralLabel>Data Corruption Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field determines whether an sObject will be corrupted on the next run.</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Custom_Object__c.field-meta.xml
<CustomField>
    <fullName>Custom_Object__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether to append &apos;__c&apos; to the end of an sObject label.</description>
    <label>Custom Object?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Delete_Records__c.field-meta.xml
<CustomField>
    <fullName>Delete_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A property to determine if records should be corrupted via deletion.</description>
    <label>Delete Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Modify_Records__c.field-meta.xml
<CustomField>
    <fullName>Modify_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A property to determine if records should be corrupted via field modification.</description>
    <label>Modify Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Number_Fields_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Number_Fields_To_Corrupt__c</fullName>
    <description>A semicolon separated list of Field API Names (including &apos;__c&apos; if necessary) that are to be corrupted by the Data Recovery Simulation code. These fields must be editable NUMBER fields.</description>
    <label>Number Field(s) To Corrupt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Text_Fields_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Text_Fields_To_Corrupt__c</fullName>
    <description>A semicolon separated list of Field API Names (including &apos;__c&apos; if necessary) that are to be corrupted by the Data Recovery Simulation code. These fields must be editable TEXT fields.</description>
    <label>Text Field(s) To Corrupt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_QueueableJobChain_Test.cls
/*
 * Copyright (c) 2025 Block, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@isTest
private class DX_QueueableJobChain_Test {
    @isTest
    static void testQueueableJobChain_chainFirst() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = false;
        testingMetadata.Modify_Records__c = true;

        DX_QueueableJobChain chain = new DX_QueueableJobChain();
        
        test.startTest();
            chain.chainFirst(new DX_DataCorruptionQueueable(chain, testingMetadata, 'testing@yourcompany.com'));
        test.stopTest();

        System.assertEquals(1, chain.getSize(), 'Verify that there is one item in the chain.');
    }

    @isTest
    static void testQueueableJobChain_chainLast() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = false;
        testingMetadata.Modify_Records__c = true;

        DX_QueueableJobChain chain = new DX_QueueableJobChain();
        
        test.startTest();
            chain.chainLast(new DX_DataCorruptionQueueable(chain, testingMetadata, 'testing@yourcompany.com'));
        test.stopTest();

        System.assertEquals(1, chain.getSize(), 'Verify that there is one item in the chain.');
    }

    @isTest
    static void testQueueableJobChain_chainFirstLast() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = false;
        testingMetadata.Modify_Records__c = true;
        
        DX_QueueableJobChain chain = new DX_QueueableJobChain();
        
        test.startTest();
            chain.chainLast(new DX_DataCorruptionQueueable(chain, testingMetadata, 'testing@yourcompany.com'));
            chain.chainFirst(new DX_DataCorruptionQueueable(chain, testingMetadata, 'testing@yourcompany.com'));
        test.stopTest();

        System.assertEquals(2, chain.getSize(), 'Verify that there is one item in the chain.');
    }

    @isTest
    static void testQueueableJobChain_runNext() {
        DX_QueueableJobChain chain = new DX_QueueableJobChain();
        
        test.startTest();
            chain.runNext();
        test.stopTest();

        System.assertEquals(0, chain.getSize(), 'Verify that there are no items in the chain.');
    }

}