force-app/main/default/objects/Data_Corruption_Object__mdt/Data_Corruption_Object__mdt.object-meta.xml
<CustomObject>
    <description>A custom metadata type to track sObjects and fields that should be corrupted by the Data Recovery Simulation code.</description>
    <label>Data Corruption Object</label>
    <pluralLabel>Data Corruption Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field determines whether an sObject will be corrupted on the next run.</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Corruption_Order__c.field-meta.xml
<CustomField>
    <fullName>Corruption_Order__c</fullName>
    <description>The order in which fields should be corrupted, with 1 being first, 2 being second, and so on.</description>
    <label>Corruption Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Custom_Object__c.field-meta.xml
<CustomField>
    <fullName>Custom_Object__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether to append &apos;__c&apos; to the end of an sObject label.</description>
    <label>Custom Object?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Delete_Records__c.field-meta.xml
<CustomField>
    <fullName>Delete_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A property to determine if records should be corrupted via deletion.</description>
    <label>Delete Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Hard_Delete_Records__c.field-meta.xml
<CustomField>
    <fullName>Hard_Delete_Records__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Optionally hard delete records for a given sObject.</description>
    <label>Hard Delete Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Modify_Records__c.field-meta.xml
<CustomField>
    <fullName>Modify_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A property to determine if records should be corrupted via field modification.</description>
    <label>Modify Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Number_Fields_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Number_Fields_To_Corrupt__c</fullName>
    <description>A semicolon separated list of Field API Names (including &apos;__c&apos; if necessary) that are to be corrupted by the Data Recovery Simulation code. These fields must be editable NUMBER fields.</description>
    <label>Number Field(s) To Corrupt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Percent_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Percent_To_Corrupt__c</fullName>
    <description>The percentage of each sObject that should be corrupted.</description>
    <label>Percent To Corrupt</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Text_Fields_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Text_Fields_To_Corrupt__c</fullName>
    <description>A semicolon separated list of Field API Names (including &apos;__c&apos; if necessary) that are to be corrupted by the Data Recovery Simulation code. These fields must be editable TEXT fields.</description>
    <label>Text Field(s) To Corrupt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_CustomMetadataSelector.cls
/*
 * Copyright (c) 2025 Block, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

public without sharing class DX_CustomMetadataSelector {
    /**
     * @description: selects and sorts active Data_Corruption_Object__mdt records
     */
    public List<Data_Corruption_Object__mdt> selectActiveDataCorruptionObjects() {
       return DX_Query.records([SELECT Masterlabel,
                DeveloperName,
                Number_Fields_To_Corrupt__c,
                Text_Fields_To_Corrupt__c,
                Custom_Object__c,
                Corruption_Order__c,
                Delete_Records__c,
                Hard_Delete_Records__c,
                Modify_Records__c,
                Percent_To_Corrupt__c
            FROM Data_Corruption_Object__mdt
            WHERE Active__c = true
            ORDER BY Corruption_Order__c ASC NULLS LAST]);
    }
}