force-app/main/default/objects/Data_Corruption_Object__mdt/Data_Corruption_Object__mdt.object-meta.xml
<CustomObject>
    <description>A custom metadata type to track sObjects and fields that should be corrupted by the Data Recovery Simulation code.</description>
    <label>Data Corruption Object</label>
    <pluralLabel>Data Corruption Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field determines whether an sObject will be corrupted on the next run.</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Custom_Object__c.field-meta.xml
<CustomField>
    <fullName>Custom_Object__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether to append &apos;__c&apos; to the end of an sObject label.</description>
    <label>Custom Object?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Delete_Records__c.field-meta.xml
<CustomField>
    <fullName>Delete_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A property to determine if records should be corrupted via deletion.</description>
    <label>Delete Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Modify_Records__c.field-meta.xml
<CustomField>
    <fullName>Modify_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A property to determine if records should be corrupted via field modification.</description>
    <label>Modify Records</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Number_Fields_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Number_Fields_To_Corrupt__c</fullName>
    <description>A semicolon separated list of Field API Names (including &apos;__c&apos; if necessary) that are to be corrupted by the Data Recovery Simulation code. These fields must be editable NUMBER fields.</description>
    <label>Number Field(s) To Corrupt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Percent_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Percent_To_Corrupt__c</fullName>
    <description>The percentage of each sObject that should be corrupted.</description>
    <label>Percent To Corrupt</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Data_Corruption_Object__mdt/fields/Text_Fields_To_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Text_Fields_To_Corrupt__c</fullName>
    <description>A semicolon separated list of Field API Names (including &apos;__c&apos; if necessary) that are to be corrupted by the Data Recovery Simulation code. These fields must be editable TEXT fields.</description>
    <label>Text Field(s) To Corrupt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_DataCorruption_Test.cls
/*
 * Copyright (c) 2025 Block, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@isTest
private class DX_DataCorruption_Test {
    
    /**
     * @description: wrapper class for mocked cases
     */
    private class Mocking {
        List<Case> mockedCases;
    }

    static Mocking returnMock() {
        Mocking result = new Mocking(); 

        result.mockedCases = new List<Case>();

        for(Integer ii=0; ii < 100; ii++) {
            Case mockCase = new Case();
            mockCase.Description = 'Mocked Case';
            mockCase.Id = (Id) DX_IdMocker.getMockId(mockCase);
            result.mockedCases.add(mockCase);
        }

        return result;
    }

    @isTest
    static void testSObjectCorruption_buildQuery() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = true;
        testingMetadata.Modify_Records__c = true;
        testingMetadata.Percent_To_Corrupt__c = 1;

        Test.startTest();
            DX_DataCorruptionHelper helper = new DX_DataCorruptionHelper(testingMetadata);
            String query = helper.buildQuery();
        Test.stopTest();

        Assert.isTrue(query.contains('Case'), 'Expected to have Case in query.');

    }

    @isTest
    static void testSObjectCorruption_testChaining() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = true;
        testingMetadata.Modify_Records__c = true;
        testingMetadata.Percent_To_Corrupt__c = 1;

        DX_Query.setMock(new QueryMock(new List<Data_Corruption_Object__mdt>{testingMetadata}));

        Test.startTest();
            DX_DataCorruptionQueueableChain job = new DX_DataCorruptionQueueableChain('testing@yourcompany.com');
            job.runJob();
        Test.stopTest();

        Assert.areEqual(1, job.chain.getSize(), 'Expected there to be one chain in the jobs chain.');
    }

    @isTest
    static void testSObjectCorruption_testBatchStart() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = true;
        testingMetadata.Modify_Records__c = true;
        testingMetadata.Percent_To_Corrupt__c = 1;

        DX_DataCorruptionBatch batch = new DX_DataCorruptionBatch(new DX_QueueableJobChain(), testingMetadata, 'testing@yourcompany.com');
        batch.helper.withMocks();

        Mocking mock = returnMock();

        Test.startTest();
            batch.start(null);
        Test.stopTest();

        Assert.isTrue(batch.corruptionQuery.contains('Case'), 'Expected to have Case in query.');
    }

    @isTest
    static void testSObjectCorruption_testBatchExecute() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = true;
        testingMetadata.Modify_Records__c = true;
        testingMetadata.Percent_To_Corrupt__c = 1;

        DX_DataCorruptionBatch batch = new DX_DataCorruptionBatch(new DX_QueueableJobChain(), testingMetadata, 'testing@yourcompany.com');
        batch.helper.withMocks();

        Mocking mock = returnMock();

        Test.startTest();
            batch.execute(null, mock.mockedCases);
        Test.stopTest();

        Assert.areEqual(50, batch.helper.modifiedRecords.size(), 'Expected there to be 50 cases left after 50% deletion for 100% corruption.');
        Assert.areEqual(50, batch.helper.deletedRecords.size(), 'Expected there to be 50 cases left after 50% deletion for 100% corruption.');
    }

    @isTest
    static void testSObjectCorruption_testBatchFinish() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = true;
        testingMetadata.Modify_Records__c = true;
        testingMetadata.Percent_To_Corrupt__c = 1;

        DX_DataCorruptionBatch batch = new DX_DataCorruptionBatch(new DX_QueueableJobChain(), testingMetadata, 'testing@yourcompany.com');
        batch.helper.withMocks();

        Mocking mock = returnMock();

        Test.startTest();
            batch.finish(null);
        Test.stopTest();

        List<EmailMessage> emails = [SELECT Id FROM EmailMessage];

        Assert.areEqual(1, emails.size(), 'Expected there to be one email sent.');
    }

    @isTest
    static void testSObjectCorruption_testDeleteAndCorrupt() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = true;
        testingMetadata.Modify_Records__c = true;
        testingMetadata.Percent_To_Corrupt__c = 1;

        DX_DataCorruptionHelper helper = new DX_DataCorruptionHelper(testingMetadata);

        helper.withMocks();

        Mocking mock = returnMock();

        Test.startTest();
            helper.corruptData(mock.mockedCases);
        Test.stopTest();

        Assert.areEqual(50, helper.modifiedRecords.size(), 'Expected there to be 50 cases left after 50% modification for 100% corruption.');
        Assert.areEqual(50, helper.deletedRecords.size(), 'Expected there to be 50 cases left after 50% deletion for 100% corruption.');
    }

    @isTest
    static void testSObjectCorruption_testDelete() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = true;
        testingMetadata.Modify_Records__c = false;
        testingMetadata.Percent_To_Corrupt__c = 1;

        DX_DataCorruptionHelper helper = new DX_DataCorruptionHelper(testingMetadata);

        helper.withMocks();

        Mocking mock = returnMock();

        Test.startTest();
            helper.corruptData(mock.mockedCases);
        Test.stopTest();

        Assert.areEqual(0, helper.modifiedRecords.size(), 'Expected there to be 0 cases left after 100% deletion for 100% corruption.');
        Assert.areEqual(100, helper.deletedRecords.size(), 'Expected there to be 100 cases deleted for 100% corruption.');
    }

    @isTest
    static void testSObjectCorruption_testModify() {
        Data_Corruption_Object__mdt testingMetadata = new Data_Corruption_Object__mdt();
        testingMetadata.Masterlabel = 'Case';
        testingMetadata.Active__c = true;
        testingMetadata.Number_Fields_To_Corrupt__c = null;
        testingMetadata.Text_Fields_To_Corrupt__c = 'Description';
        testingMetadata.Custom_Object__c = false;
        testingMetadata.Delete_Records__c = false;
        testingMetadata.Modify_Records__c = true;
        testingMetadata.Percent_To_Corrupt__c = 1;
        
        DX_DataCorruptionHelper helper = new DX_DataCorruptionHelper(testingMetadata);

        helper.withMocks();

        Mocking mock = returnMock();

        Test.startTest();
            helper.corruptData(mock.mockedCases);
        Test.stopTest();

        Assert.areEqual(100, helper.modifiedRecords.size(), 'Expected there to be 100 modified cases left after 0% deletion for 100% corruption.');
        Assert.areEqual(0, helper.deletedRecords.size(), 'Expected there to be 0 cases deleted.');
    }

    class QueryMock extends DX_Query.Service
    {
        final List<SObject> records;
        QueryMock(List<SObject> records)
        {
            this.records = records;
        }

        protected override List<SObject> passThrough(List<SObject> toIgnore)
        {
            return records;
        }
    }
}